# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: historical_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - historical-data:/var/lib/postgresql/data

volumes:
  historical-data: